[default]
DEBUG = false
TITLE = "Red Boar Inn"

EXTENSIONS = [
"app.extensions.configuration:init_app"
]


[production]
SECRET_KEY = "@jinja {{env.SECRET_KEY}}"
MONGO_URI = "@jinja {{env.DATABASE_URL}}"
MONGO_URI_UPDATES = "@jinja {{env.DATABASE_URL_UPDATES}}"


[development]
SECRET_KEY = 'secret'
MONGO_URI = "@jinja {{env.DATABASE_URL}}"
MONGO_URI_UPDATES = "@jinja {{env.DATABASE_URL_UPDATES}}"


[test]
SECRET_KEY = 'secret'
WTF_CSRF_ENABLED = false